Timestamped
matsbror/wabench pull request #3
Opened 2023-07-11 14:00 UTC by sangeeta1998

2023-07-18 14:05 UTC, sangeeta1998 commented
@matsbror

2023-07-19 09:38 UTC, matsbror requested changes
There are too many changes in the code formatting to make it reasonable to make a proper review. Do you have a setting in the editor that automatically reformats the code? Maybe you can turn that off. 

Please make changes according to my comments in all codes and then tell me when done. In summary these are:

* Remove all changes you made that are not about timestamps
* Use timestamps in ms since epoch (google time since epoch, if you do not know what it is)
* The output should be:
   -  timestamp for the start of the program (to be used to calculate the startup time based on timestamp in the  runtime)
   - execution time of the relevant part of the benchmark (I would prefer the timestamps also here, but it might not be convenient for programs with multiple timestamps)

2023-07-19 09:38 UTC, matsbror commented on MiBench/automotive/basicmath/src/basicmath_large.c
> +  cpu_time_used = ((double) (end - start)) / CLOCKS_PER_SEC;
Why do you divide with `CLOCKS_PER_SEC`

2023-07-19 09:38 UTC, matsbror commented on MiBench/automotive/basicmath/src/basicmath_large.c
> +  start = clock();
In this code, it becomes overly complicated to start and stop the clock. It should be sufficient with one measurement period.

2023-07-19 09:38 UTC, matsbror commented on MiBench/automotive/basicmath/src/basicmath_large.c
> +  end_main=clock(); //timestamp to end main
Why do you take this time stamp here?

2023-07-19 09:38 UTC, matsbror commented on MiBench/automotive/basicmath/src/basicmath_large.c
> +  cpu_time_used = ((double) (end - start)) / CLOCKS_PER_SEC;
Again, it's time you want to track, so remove this division and others of the same kind. I suggest to output a timestamp as ms since epoch.

2023-07-19 09:38 UTC, matsbror commented on MiBench/automotive/basicmath/src/basicmath_large.c
> +  printf("Time taken for startup: %2f seconds\n", cpu_time_used_main);
This printout does not make sense. You want to measure the time from when the runtime starts loading the wasm file until it starts execute. This means you need to instrument each runtime to print this timestamp and then you need to calaculate the time afterwards.

2023-07-19 09:38 UTC, matsbror commented on MiBench/automotive/bitcount/src/bitcnts.c
> -double seconds_now()
was this in the original code? If so, do not remove it.

2023-07-19 09:38 UTC, matsbror commented on MiBench/automotive/bitcount/src/bitcnts.c
> +  if (argc < 2) {
please do not change the formatting of the original code. It makes code review more difficult.

2023-07-19 09:38 UTC, matsbror commented on MiBench/automotive/bitcount/src/bitcnts.c
> -	    cmin = ct;
again, you have changed the format. I explicitly asked you earlier not to do this.

2024-10-13 10:22 UTC, closed without merging